//<auto-generated>
#region License
//-----------------------------------------------------------------------
// <copyright>
//     Copyright matatabi-ux 2014.
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace ResponsiveNaviBarSample.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;
    using System.Threading.Tasks;
    using System.Xml.Serialization;

    /// <summary>
    /// アプリケーション設定情報 のインタフェース
    /// </summary>
    public partial interface IApplicationSettings
    {
        List<PhotoItem> Photos { get; set; }
    }

    /// <summary>
    /// アプリケーション設定情報
    /// </summary>
    [XmlRoot("app-settings")]
    public partial class ApplicationSettings : IApplicationSettings
    {
        #region Photos:写真情報 プロパティ
        /// <summary>
        /// 写真情報
        /// </summary>
        private List<PhotoItem> photos; 

        /// <summary>
        /// 写真情報 の取得および設定
        /// </summary>
        [XmlElement("photo")]
        public List<PhotoItem> Photos
        {
            get { return this.photos; }
            set { this.photos = value; }
        }
        #endregion //Photos:写真情報 プロパティ

    }

}