//<auto-generated>
#region License
//-----------------------------------------------------------------------
// <copyright>
//     Copyright matatabi-ux 2014.
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace ResponsiveNaviBarSample.Framework
{
    /// <summary>
    /// 解放可能なインスタンスのインタフェース
    /// </summary>
    public interface ICleanup
    {
        /// <summary>
        /// インスタンスを解放します
        /// </summary>
        void Cleanup();
    }
}
