//<auto-generated>
#region License
//-----------------------------------------------------------------------
// <copyright>
//     Copyright matatabi-ux 2014.
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace ResponsiveNaviBarSample.Presenters
{
    using ResponsiveNaviBarSample.ViewModels;
    using Windows.UI.Xaml;

    /// <summary>
    /// Presenter のインタフェース
    /// </summary>
    public interface IPresenter
    {
        /// <summary>
        /// 初期化
        /// </summary>
        void Initialize();

        /// <summary>
        /// 終了処理
        /// </summary>
        void Discard();
    }

    /// <summary>
    /// Presenter のインタフェース
    /// </summary>
    /// <typeparam name="TView">Page</typeparam>
    /// <typeparam name="TViewModel">PageViewModel</typeparam>
    public interface IPresenter<TView, TViewModel> : IPresenter
        where TView : FrameworkElement
        where TViewModel : ViewModelBase, new()
    {
        /// <summary>
        /// Page
        /// </summary>
        TView View { get; set; }

        /// <summary>
        /// PageViewModel
        /// </summary>
        TViewModel ViewModel { get; set; }
    }
}
