//<auto-generated>
#region License
//-----------------------------------------------------------------------
// <copyright>
//     Copyright matatabi-ux 2014.
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace ResponsiveNaviBarSample.Views
{
    using ResponsiveNaviBarSample.Presenters;

    /// <summary>
    /// Presenter を持つ基底ページクラスのインタフェース
    /// </summary>
    /// <typeparam name="TPresenter"></typeparam>
    public interface IView<TPresenter> where TPresenter : IPresenter
    {
        /// <summary>
        /// Presenter の Get アクセサ
        /// </summary>
        TPresenter Presenter { get; }
    }
}
