//<auto-generated>
#region License
//-----------------------------------------------------------------------
// <copyright>
//     Copyright matatabi-ux 2014.
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace ResponsiveNaviBarSample.ViewModels
{
    using System.Runtime.Serialization;
    using ResponsiveNaviBarSample.Common;
    using ResponsiveNaviBarSample.Framework;

    /// <summary>
    /// PageViewModel 基底クラス
    /// </summary>
    [DataContract]
    public class ViewModelBase : BindableBase, ICleanup
    {
        /// <summary>
        /// 初期化処理
        /// </summary>
        public virtual void Initialize()
        {
        }

        /// <summary>
        /// 終了処理
        /// </summary>
        public virtual void Discard()
        {
            this.Cleanup();
        }

        /// <summary>
        /// インスタンスを解放します
        /// </summary>
        public virtual void Cleanup()
        {
        }
    }
}
